"""FastAPI endpoints for Strategy Signals query and management (Phase 6)."""

import logging
from typing import Any, Dict, List, Optional
from fastapi import APIRouter, HTTPException, Query, status

from app.db.repository import TradeRepository
from app.db.session import get_db_session

logger = logging.getLogger("delta_bot.api.signals")
router = APIRouter(prefix="/signals", tags=["Signals"])


@router.get("", response_model=List[Dict[str, Any]])
async def get_signals(
    symbol: Optional[str] = Query(None, description="Filter by symbol, e.g. BTCUSD"),
    timeframe: Optional[str] = Query(None, description="Filter by resolution, e.g. 5m, 15m, 1h"),
    strategy_name: Optional[str] = Query(None, description="Filter by strategy name"),
    status_filter: Optional[str] = Query(None, alias="status", description="Filter by status, e.g. PENDING, PROMOTED"),
    limit: int = Query(50, ge=1, le=200, description="Max signals to return"),
) -> List[Dict[str, Any]]:
    """Queries candidate signals generated by the Strategy Engine with flexible filtering."""
    try:
        async with get_db_session() as session:
            signals = await TradeRepository.get_filtered_signals(
                session=session,
                symbol=symbol,
                timeframe=timeframe,
                strategy_name=strategy_name,
                status=status_filter,
                limit=limit,
            )
            return [s.to_dict() for s in signals]
    except Exception as e:
        logger.error(f"Error querying signals: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to fetch signals: {str(e)}",
        )


@router.get("/{signal_id}", response_model=Dict[str, Any])
async def get_signal_by_id(signal_id: int) -> Dict[str, Any]:
    """Retrieves a single candidate signal by ID."""
    async with get_db_session() as session:
        signal = await TradeRepository.get_signal_by_id(session, signal_id)
        if not signal:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"Signal ID {signal_id} not found.",
            )
        return signal.to_dict()


@router.post("/{signal_id}/execute", response_model=Dict[str, Any])
async def execute_signal(signal_id: int) -> Dict[str, Any]:
    """Promotes a generated signal into a trade and executes it through the full lifecycle."""
    try:
        from app.services.strategy_engine import strategy_engine

        result = await strategy_engine.auto_execute_generated_signal(signal_id=signal_id)
        return result.model_dump()
    except ValueError as exc:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=str(exc))
    except Exception as exc:
        logger.error(f"Error auto-executing signal {signal_id}: {exc}", exc_info=True)
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=str(exc))
