"""Trade Decisions, 7-State Lifecycle, Signals, and Audit Routes."""

import logging
from typing import List, Optional
from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.session import get_db
from app.db.enums import TradeLifecycleState
from app.db.repository import TradeRepository
from app.schemas.trade import (
    SignalCreate,
    SignalResponse,
    TradeDecisionCreate,
    TradeDecisionResponse,
    TradeDecisionUpdateState,
)
from app.schemas.audit import AuditLogResponse

logger = logging.getLogger("delta_bot.api.trades")
router = APIRouter(tags=["Trades & Lifecycle"])


# =============================================================================
# 1. TRADE DECISIONS & 7-STATE LIFECYCLE
# =============================================================================

@router.get("/trades", response_model=List[TradeDecisionResponse])
async def list_trade_decisions(
    symbol: Optional[str] = Query(default=None),
    state: Optional[str] = Query(default=None),
    active_only: bool = Query(default=False),
    limit: int = Query(default=50, le=200),
    db: AsyncSession = Depends(get_db),
):
    """Lists trade decisions tracking the 7-State Lifecycle."""
    trades = await TradeRepository.get_trade_decisions(
        session=db, symbol=symbol, state=state, active_only=active_only, limit=limit
    )
    return trades


@router.get("/trades/{trade_id}", response_model=TradeDecisionResponse)
async def get_trade_decision(trade_id: int, db: AsyncSession = Depends(get_db)):
    """Retrieves a specific trade decision with its linked orders and position timeline."""
    trade = await TradeRepository.get_trade_decision(session=db, decision_id=trade_id)
    if not trade:
        raise HTTPException(status_code=404, detail=f"Trade #{trade_id} not found")
    return trade


@router.post("/trades", response_model=TradeDecisionResponse, status_code=status.HTTP_201_CREATED)
async def create_trade_decision(payload: TradeDecisionCreate, db: AsyncSession = Depends(get_db)):
    """Initiates a new trade decision in 'SIGNAL_GENERATED' state.
    Enforces the invariant: at most ONE active trade per instrument.
    """
    try:
        trade = await TradeRepository.create_trade_decision(
            session=db,
            symbol=payload.symbol,
            direction=payload.direction.value,
            subaccount=payload.subaccount,
            is_paper=payload.is_paper,
            timeframe_alignment=payload.timeframe_alignment,
            entry_price=payload.entry_price,
            take_profit_price=payload.take_profit_price,
            stop_loss_price=payload.stop_loss_price,
            leverage=payload.leverage,
            suggested_size=payload.suggested_size,
        )
        return trade
    except ValueError as err:
        raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail=str(err))


@router.patch("/trades/{trade_id}/state", response_model=TradeDecisionResponse)
async def transition_trade_state(
    trade_id: int,
    payload: TradeDecisionUpdateState,
    db: AsyncSession = Depends(get_db),
):
    """Transitions a trade decision to the next state in the 7-State Lifecycle:
    SIGNAL_GENERATED -> VALIDATING -> LLM_CONFIRMED -> RISK_VALIDATED -> ORDER_SUBMITTED -> POSITION_OPEN -> EXITED
    """
    try:
        trade = await TradeRepository.transition_trade_state(
            session=db,
            decision_id=trade_id,
            target_state=payload.state,
            notes=payload.notes,
            llm_approved=payload.llm_approved,
            llm_confidence=payload.llm_confidence,
            llm_reasoning=payload.llm_reasoning,
            risk_approved=payload.risk_approved,
            risk_notes=payload.risk_notes,
            exit_price=payload.exit_price,
            exit_reason=payload.exit_reason,
            realized_pnl=payload.realized_pnl,
        )
        return trade
    except ValueError as err:
        raise HTTPException(status_code=400, detail=str(err))


# =============================================================================
# 2. SIGNALS
# =============================================================================

@router.get("/signals", response_model=List[SignalResponse])
async def list_signals(
    symbol: Optional[str] = Query(default=None),
    limit: int = Query(default=50, le=200),
    db: AsyncSession = Depends(get_db),
):
    """Retrieves strategy candidate signals."""
    signals = await TradeRepository.get_recent_signals(session=db, symbol=symbol, limit=limit)
    return signals


@router.post("/signals", response_model=SignalResponse, status_code=status.HTTP_201_CREATED)
async def record_signal(payload: SignalCreate, db: AsyncSession = Depends(get_db)):
    """Records a candidate technical signal generated by an active strategy."""
    sig = await TradeRepository.record_signal(
        session=db,
        strategy_name=payload.strategy_name,
        symbol=payload.symbol,
        timeframe=payload.timeframe,
        side=payload.side,
        trigger_price=payload.trigger_price,
        confidence_score=payload.confidence_score,
        indicator_snapshot=payload.indicator_snapshot,
    )
    return sig


# =============================================================================
# 3. AUDIT TRAIL
# =============================================================================

@router.get("/audit-logs", response_model=List[AuditLogResponse])
async def get_audit_logs(
    severity: Optional[str] = Query(default=None),
    event_type: Optional[str] = Query(default=None),
    limit: int = Query(default=100, le=500),
    db: AsyncSession = Depends(get_db),
):
    """Fetches system, risk, and invariant execution audit records."""
    logs = await TradeRepository.get_audit_logs(
        session=db, severity=severity, event_type=event_type, limit=limit
    )
    return logs
